# Build and deploy portfolio to GitHub Pages
name: Build and Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: "npm"
          
      - name: Install dependencies
        run: npm ci -f
        
      - name: Build application
        run: npm run build
        
      - name: Deploy to GitHub Pages (this repo)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
        
      - name: Deploy to external GitHub Pages repository
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Validate that GH_TOKEN is available
          if [ -z "$GH_TOKEN" ]; then
            echo "Error: GH_TOKEN secret is not set. Please configure a Personal Access Token."
            exit 1
          fi
          
          # Clone the target repository
          echo "Cloning jounaidayoub.github.io repository..."
          git clone https://jounaidayoub:${GH_TOKEN}@github.com/Jounaidayoub/jounaidayoub.github.io.git gh-pages-repo
          
          # Configure git
          cd gh-pages-repo
          git config user.name "Ayoub"
          git config user.email "123956897+Jounaidayoub@users.noreply.github.com"
          
          # Remove GitHub Actions authentication header to avoid conflicts
          git config --unset-all http.https://github.com/.extraheader
          
          # Clear existing content (except .git)
          find . -maxdepth 1 ! -name '.git' ! -name '.' ! -name '..' -exec rm -rf {} +
          
          # Copy new build files
          echo "Copying build files..."
          cp -r ../dist/* .
          
          # Check if there are any changes
          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes to deploy"
            exit 0
          fi
          
          # Commit and push changes
          git add .
          git commit -m "Deploy to GitHub Pages ${{ github.sha }}"
          git push https://jounaidayoub:${GH_TOKEN}@github.com/Jounaidayoub/jounaidayoub.github.io.git main
          
          echo "✅ Successfully deployed to external GitHub Pages!"
          echo "🌐 Site will be available at: https://jounaidayoub.github.io"
          echo "🌐 Custom domain: https://ayooub.me (if DNS is configured)"
